# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-17 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolar',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('compra', models.TextField(blank=True, null=True)),
                ('venda', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
